// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkSc2Y4Kx8ikH4Cj_Rxib1-8MHiqbNuoA',
    appId: '1:770407907852:web:f032e6b77ac0a24d0ea429',
    messagingSenderId: '770407907852',
    projectId: 'corner-c4026',
    authDomain: 'corner-c4026.firebaseapp.com',
    storageBucket: 'corner-c4026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7v7dEkBDObaEIKuE-O-o4fzaugYq4WQc',
    appId: '1:770407907852:android:39cdabdfe309545c0ea429',
    messagingSenderId: '770407907852',
    projectId: 'corner-c4026',
    storageBucket: 'corner-c4026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpvL_B9vpmmHx86y98tUw0ussChgMYpsE',
    appId: '1:770407907852:ios:381618e61c082a3e0ea429',
    messagingSenderId: '770407907852',
    projectId: 'corner-c4026',
    storageBucket: 'corner-c4026.firebasestorage.app',
    iosBundleId: 'com.example.corner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpvL_B9vpmmHx86y98tUw0ussChgMYpsE',
    appId: '1:770407907852:ios:381618e61c082a3e0ea429',
    messagingSenderId: '770407907852',
    projectId: 'corner-c4026',
    storageBucket: 'corner-c4026.firebasestorage.app',
    iosBundleId: 'com.example.corner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkSc2Y4Kx8ikH4Cj_Rxib1-8MHiqbNuoA',
    appId: '1:770407907852:web:e533b946ee919e7b0ea429',
    messagingSenderId: '770407907852',
    projectId: 'corner-c4026',
    authDomain: 'corner-c4026.firebaseapp.com',
    storageBucket: 'corner-c4026.firebasestorage.app',
  );
}
